title: SmartPark
owner_name: Mihir Bapat
github_username: Hypernova101
github_repo: "parking_frontend" 
baseurl: "/parking_frontend"
future: true
remote_theme: jekyll/minima
minima:
  skin: classic
# remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: pages-themes/dinky@v0.2.0
# remote_theme: pages-themes/minimal@v0.2.0
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: pages-themes/time-machine@v0.2.0
plugins:
  - jekyll-remote-theme
header_pages:
 # - navigation/worlds/home.md
#  - navigation/titanic.md
 # - navigation/map.md
  #- navigation/aboutus.md
 # - navigation/search.md
  #- navigation/bootstrap/landing.md